# Generated by Django 4.1.2 on 2022-10-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_file",
            field=models.ImageField(null=True, upload_to="avatars"),
        ),
    ]
